#plugins:
#  - jekyll-remote-theme

#remote_theme: zivhub/monophase@main
remote_theme: pages-themes/primer
#remote_theme: eecs485staff/primer-spec
#remote_theme: riggraz/no-style-please

name: Ernesto Nicola's Home Page
title: null
#title: Curso de Astronomía 2022 en Palma de Mallorca
#description: A short description of your site's purpose
#name: Ernesto Nicola

#github:
#  private: true
