#plugins:
#  - jekyll-remote-theme

remote_theme: pages-themes/primer
#remote_theme: zivhub/monophase@main
#remote_theme: eecs485staff/primer-spec
#remote_theme: riggraz/no-style-please

name: Ernesto Nicola's Home Page
#title: null
#description: A short description of your site's purpose

#github:
#  private: true
